language: r
r: bioc-devel
sudo: TRUE

os: linux
#   - linux
#  - windows
#  - osx


repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org


notifications:
  email: TRUE


cache:
  - packages
  - ccache

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'


script:
  - travis_wait 40 R CMD build
  - R CMD check *tar.gz


before_install:
  - R -q -e 'install.packages(c("BH", "Rcpp", "RcppEigen",
                                "StanHeaders", "rstantools",
                                "rstan", "covr"))'
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars



after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'

